name: GitHub Actions Demo
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: eslint . --fix
      
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: echo "check current commit is prettier"
      - run: prettier --check "src/**/*.js"