name: GitHub Actions Demo
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn eslint . --fix
      
  prettier:
    runs-on: ubuntu-latest
    steps:
      - run: echo "check current commit is prettier"
      - run: yarn prettier --check "src/**/*.js"